### ISSUE TITLE
Hello when i try to use it this is what i get. Any help ?

### ISSUE THREAD

**Issue by Elementalix** [kotcrab/fate-explorer#3]
Extracting: C:\Users\Skewes\Downloads\fate-tools\archive.pk
Output folder: C:\Users\Skewes\Downloads\fate-tools\out\archive
Reading file dictionary...
597517183 directories, 1556596034 files
java.io.EOFException
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
        at com.kotcrab.fate.io.FateInputStream.readInt(FateInputStream.kt:56)
        at com.kotcrab.fate.file.extella.PkFile.<init>(PkFile.kt:54)
        at com.kotcrab.fate.file.extella.PkFile.<init>(PkFile.kt:27)
        at com.kotcrab.fate.cli.PkToolsCommand.extractPk(PkToolsCli.kt:124)
        at com.kotcrab.fate.cli.ExtractDnD.run(PkToolsCli.kt:59)
        at com.kotcrab.fate.cli.FateCli.stdCliLauncher(FateCli.kt:81)
        at com.kotcrab.fate.cli.FateCli.stdCliLauncher(FateCli.kt:74)
        at com.kotcrab.fate.cli.PkToolsCli.main(PkToolsCli.kt:35)
Operation finished, press any key to close this window...

**Comment by kotcrab** [comment]
You need to decrypt the archive first. E.g. if it's from Vita then you can use psvpfstools.

**Comment by Elementalix** [comment]
Hello here the info/download site.
https://nicoblog.org/psvita/fate-extella-link-jpn-nonpdrm-psvita/

**Comment by kotcrab** [comment]
@Elementalix I've removed your comment, do not post links to copyrighted content

**Comment by Elementalix** [comment]
Ok, then the info is here

PlayStation Vita (PS Vita)
Japan (NTSC-J)
NoNpDrm
PCSG01091
1.29 GB

**Comment by kotcrab** [comment]
There's no point in posting this, people who want to find it will find it anyway. If you need help with decryption you can look for a thread on XeNTaX forums, there was an explanation there.
